version: '3'

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - ./certs:/app/certs
    command: npm run dev
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - app
